# Make sure to run the README.md usage example on commits.
# Using wisdom from https://github.com/fchollet/keras/blob/master/.travis.yml
dist: trusty
language: python
cache: pip
matrix:
    include:
        - python: 2.7
          env: KERAS_BACKEND=tensorflow
        - python: 3.5
          env: KERAS_BACKEND=tensorflow
        - python: 3.6
          env: KERAS_BACKEND=tensorflow
install:
  - pip install tensorflow
script: python -c 'exec(open("README.md").read().split("```")[1][6:])'
